name: skycosmic
version: 0.0.9
description: A professional Flutter package providing ready-to-use UI components with CLI support, enabling rapid and consistent UI development.
homepage: https://github.com/rizaldinaldianputra/skycosmic
repository: https://github.com/rizaldinaldianputra/skycosmic
environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  skycosmic: skycosmic

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
