name: stisla
version: 0.0.1
description: Paket untuk membuat komponen Flutter Stisla dengan CLI
homepage: https://github.com/username/stisla_generator
repository: https://github.com/username/stisla_generator
environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  stisla: stisla

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
