name: stisla_generator
version: 0.0.1
description: Paket untuk membuat komponen Flutter Stisla dengan CLI
homepage: https://github.com/rizaldinaldianputra/stisla-flutter
repository: https://github.com/rizaldinaldianputra/stisla-flutter
environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  stisla: stisla

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
